python run_triple_cliqs_vec.py UD_Bulgarian-BTB word $1 $2 $3
python run_triple_cliqs_vec.py UD_Danish-DDT word $1 $2 $3
python run_triple_cliqs_vec.py UD_Wolof-WTB word $1 $2 $3
python run_triple_cliqs_vec.py UD_Arabic-NYUAD word $1 $2 $3
python run_triple_cliqs_vec.py UD_Basque-BDT word $1 $2 $3
python run_triple_cliqs_vec.py UD_Finnish-FTB word $1 $2 $3
python run_triple_cliqs_vec.py UD_Czech-FicTree word $1 $2 $3
python run_triple_cliqs_vec.py UD_Classical_Chinese-Kyoto word $1 $2 $3
python run_triple_cliqs_vec.py UD_English-LinES word $1 $2 $3
python run_triple_cliqs_vec.py UD_Korean-GSD word $1 $2 $3
python run_triple_cliqs_vec.py UD_Uyghur-UDT word $1 $2 $3
python run_triple_cliqs_vec.py UD_Norwegian-Nynorsk word $1 $2 $3
python run_triple_cliqs_vec.py UD_Catalan-AnCora word $1 $2 $3
python run_triple_cliqs_vec.py UD_Latvian-LVTB word $1 $2 $3
python run_triple_cliqs_vec.py UD_Slovak-SNK word $1 $2 $3
python run_triple_cliqs_vec.py UD_Galician-CTG word $1 $2 $3
python run_triple_cliqs_vec.py UD_Serbian-SET word $1 $2 $3
python run_triple_cliqs_vec.py UD_Chinese-GSDSimp word $1 $2 $3
python run_triple_cliqs_vec.py UD_Afrikaans-AfriBooms word $1 $2 $3
python run_triple_cliqs_vec.py UD_Russian-SynTagRus word $1 $2 $3
python run_triple_cliqs_vec.py UD_Estonian-EDT word $1 $2 $3
python run_triple_cliqs_vec.py UD_Romanian-RRT word $1 $2 $3
python run_triple_cliqs_vec.py UD_Norwegian-Bokmaal word $1 $2 $3
python run_triple_cliqs_vec.py UD_French-Spoken word $1 $2 $3
python run_triple_cliqs_vec.py UD_Ancient_Greek-PROIEL word $1 $2 $3
python run_triple_cliqs_vec.py UD_German-GSD word $1 $2 $3
python run_triple_cliqs_vec.py UD_German-HDT word $1 $2 $3
python run_triple_cliqs_vec.py UD_Urdu-UDTB word $1 $2 $3
python run_triple_cliqs_vec.py UD_Finnish-TDT word $1 $2 $3
python run_triple_cliqs_vec.py UD_Chinese-GSD word $1 $2 $3
python run_triple_cliqs_vec.py UD_Polish-PDB word $1 $2 $3
python run_triple_cliqs_vec.py UD_Polish-LFG word $1 $2 $3
python run_triple_cliqs_vec.py UD_Latin-ITTB word $1 $2 $3
python run_triple_cliqs_vec.py UD_Portuguese-Bosque word $1 $2 $3
python run_triple_cliqs_vec.py UD_Norwegian-NynorskLIA word $1 $2 $3
python run_triple_cliqs_vec.py UD_English-ESL word $1 $2 $3
python run_triple_cliqs_vec.py UD_Greek-GDT word $1 $2 $3
python run_triple_cliqs_vec.py UD_Spanish-AnCora word $1 $2 $3
python run_triple_cliqs_vec.py UD_Slovenian-SSJ word $1 $2 $3
python run_triple_cliqs_vec.py UD_Coptic-Scriptorium word $1 $2 $3
python run_triple_cliqs_vec.py UD_Arabic-PADT word $1 $2 $3
python run_triple_cliqs_vec.py UD_Vietnamese-VTB word $1 $2 $3
python run_triple_cliqs_vec.py UD_Latin-PROIEL word $1 $2 $3
python run_triple_cliqs_vec.py UD_Dutch-Alpino word $1 $2 $3
python run_triple_cliqs_vec.py UD_Portuguese-GSD word $1 $2 $3
python run_triple_cliqs_vec.py UD_French-FTB word $1 $2 $3
python run_triple_cliqs_vec.py UD_Swedish-LinES word $1 $2 $3
python run_triple_cliqs_vec.py UD_Japanese-BCCWJ word $1 $2 $3
python run_triple_cliqs_vec.py UD_Ancient_Greek-Perseus word $1 $2 $3
python run_triple_cliqs_vec.py UD_English-GUM word $1 $2 $3
python run_triple_cliqs_vec.py UD_Romanian-Nonstandard word $1 $2 $3
python run_triple_cliqs_vec.py UD_Ukrainian-IU word $1 $2 $3
python run_triple_cliqs_vec.py UD_English-EWT word $1 $2 $3
python run_triple_cliqs_vec.py UD_Hindi-HDTB word $1 $2 $3
python run_triple_cliqs_vec.py UD_Old_French-SRCMF word $1 $2 $3
python run_triple_cliqs_vec.py UD_Croatian-SET word $1 $2 $3
python run_triple_cliqs_vec.py UD_Swedish-Talbanken word $1 $2 $3
python run_triple_cliqs_vec.py UD_Italian-VIT word $1 $2 $3
python run_triple_cliqs_vec.py UD_Czech-PDT word $1 $2 $3
python run_triple_cliqs_vec.py UD_Hungarian-Szeged word $1 $2 $3
python run_triple_cliqs_vec.py UD_Indonesian-GSD word $1 $2 $3
